var obj1 = [
    { name: 'A', age: 18 },
    { name: 'B', age: 19 },
    { name: 'C', age: 20 },
    { name: 'D', age: 21 },
    { name: 'E', age: 22 },
    { name: 'F', age: 22 },
    { name: 'G', age: 23 },
    { name: 'H', age: 24 },
    { name: 'I', age: 25 },
    { name: 'J', age: 26 },
    { name: 'AA', age: 18 },
    { name: 'BA', age: 19 },
    { name: 'CA', age: 20 },
    { name: 'DA', age: 21 },
    { name: 'EA', age: 22 },
    { name: 'FA', age: 22 },
    { name: 'GA', age: 23 },
    { name: 'HA', age: 24 },
    { name: 'IA', age: 25 },
    { name: 'JA', age: 26 },
    { name: 'AAA', age: 18 },
    { name: 'BAA', age: 19 },
    { name: 'CAA', age: 20 },
    { name: 'DAA', age: 21 },
    { name: 'EAA', age: 22 },
    { name: 'FAA', age: 22 },
    { name: 'GAA', age: 23 },
    { name: 'HAA', age: 24 },
    { name: 'IAA', age: 25 },
    { name: 'JAA', age: 26 },
    { name: 'AAAA', age: 18 },
    { name: 'BAAA', age: 19 },
    { name: 'CAAA', age: 20 },
    { name: 'DAAA', age: 21 },
    { name: 'EAAA', age: 22 },
    { name: 'FAAA', age: 22 },
    { name: 'GAAA', age: 23 },
    { name: 'HAAA', age: 24 },
    { name: 'IAAA', age: 25 },
    { name: 'JAAA', age: 26 },
    { name: 'AAAAA', age: 18 },
    { name: 'BAAAA', age: 19 },
    { name: 'CAAAA', age: 20 },
    { name: 'DAAAA', age: 21 },
    { name: 'EAAAA', age: 22 },
    { name: 'FAAAA', age: 22 },
    { name: 'GAAAA', age: 23 },
    { name: 'HAAAA', age: 24 },
    { name: 'IAAAA', age: 25 },
    { name: 'JAAAA', age: 26 },
    { name: 'QA', age: 18 },
    { name: 'QB', age: 19 },
    { name: 'QC', age: 20 },
    { name: 'QD', age: 21 },
    { name: 'QE', age: 22 },
    { name: 'QF', age: 22 },
    { name: 'QG', age: 23 },
    { name: 'QH', age: 24 },
    { name: 'QI', age: 25 },
    { name: 'QJ', age: 26 },
    { name: 'QAA', age: 18 },
    { name: 'QBA', age: 19 },
    { name: 'QCA', age: 20 },
    { name: 'QDA', age: 21 },
    { name: 'QEA', age: 22 },
    { name: 'QFA', age: 22 },
    { name: 'QGA', age: 23 },
    { name: 'QHA', age: 24 },
    { name: 'QIA', age: 25 },
    { name: 'QJA', age: 26 },
    { name: 'QAAA', age: 18 },
    { name: 'QBAA', age: 19 },
    { name: 'QCAA', age: 20 },
    { name: 'QDAA', age: 21 },
    { name: 'QEAA', age: 22 },
    { name: 'QFAA', age: 22 },
    { name: 'QGAA', age: 23 },
    { name: 'QHAA', age: 24 },
    { name: 'QIAA', age: 25 },
    { name: 'QJAA', age: 26 },
    { name: 'QAAAA', age: 18 },
    { name: 'QBAAA', age: 19 },
    { name: 'QCAAA', age: 20 },
    { name: 'QDAAA', age: 21 },
    { name: 'QEAAA', age: 22 },
    { name: 'QFAAA', age: 22 },
    { name: 'QGAAA', age: 23 },
    { name: 'QHAAA', age: 24 },
    { name: 'QIAAA', age: 25 },
    { name: 'QJAAA', age: 26 },
    { name: 'QAAAAA', age: 18 },
    { name: 'QBAAAA', age: 19 },
    { name: 'QCAAAA', age: 20 },
    { name: 'QDAAAA', age: 21 },
    { name: 'QEAAAA', age: 22 },
    { name: 'QFAAAA', age: 22 },
    { name: 'QGAAAA', age: 23 },
    { name: 'QHAAAA', age: 24 },
    { name: 'QIAAAA', age: 25 },
    { name: 'QJAAAA', age: 26 },
    { name: 'wA', age: 18 },
    { name: 'wB', age: 19 },
    { name: 'wC', age: 20 },
    { name: 'wD', age: 21 },
    { name: 'wE', age: 22 },
    { name: 'wF', age: 22 },
    { name: 'wG', age: 23 },
    { name: 'wH', age: 24 },
    { name: 'wI', age: 25 },
    { name: 'wJ', age: 26 },
    { name: 'wAA', age: 18 },
    { name: 'wBA', age: 19 },
    { name: 'wCA', age: 20 },
    { name: 'wDA', age: 21 },
    { name: 'wEA', age: 22 },
    { name: 'wFA', age: 22 },
    { name: 'wGA', age: 23 },
    { name: 'wHA', age: 24 },
    { name: 'wIA', age: 25 },
    { name: 'wJA', age: 26 },
    { name: 'wAAA', age: 18 },
    { name: 'wBAA', age: 19 },
    { name: 'wCAA', age: 20 },
    { name: 'wDAA', age: 21 },
    { name: 'wEAA', age: 22 },
    { name: 'wFAA', age: 22 },
    { name: 'wGAA', age: 23 },
    { name: 'wHAA', age: 24 },
    { name: 'wIAA', age: 25 },
    { name: 'wJAA', age: 26 },
    { name: 'wAAAA', age: 18 },
    { name: 'wBAAA', age: 19 },
    { name: 'wCAAA', age: 20 },
    { name: 'wDAAA', age: 21 },
    { name: 'wEAAA', age: 22 },
    { name: 'wFAAA', age: 22 },
    { name: 'wGAAA', age: 23 },
    { name: 'wHAAA', age: 24 },
    { name: 'wIAAA', age: 25 },
    { name: 'wJAAA', age: 26 },
    { name: 'wAAAAA', age: 18 },
    { name: 'wBAAAA', age: 19 },
    { name: 'wCAAAA', age: 20 },
    { name: 'wDAAAA', age: 21 },
    { name: 'wEAAAA', age: 22 },
    { name: 'wFAAAA', age: 22 },
    { name: 'wGAAAA', age: 23 },
    { name: 'wHAAAA', age: 24 },
    { name: 'wIAAAA', age: 25 },
    { name: 'wJAAAA', age: 26 },
]

var obj2 = [
    { name: 'QA', age: 18 },
    { name: 'QB', age: 19 },
    { name: 'QC', age: 20 },
    { name: 'QD', age: 21 },
    { name: 'QE', age: 22 },
    { name: 'QF', age: 22 },
    { name: 'QG', age: 23 },
    { name: 'QH', age: 24 },
    { name: 'QI', age: 25 },
    { name: 'QJ', age: 26 },
    { name: 'QAA', age: 18 },
    { name: 'QBA', age: 19 },
    { name: 'QCA', age: 20 },
    { name: 'QDA', age: 21 },
    { name: 'QEA', age: 22 },
    { name: 'QFA', age: 22 },
    { name: 'QGA', age: 23 },
    { name: 'QHA', age: 24 },
    { name: 'QIA', age: 25 },
    { name: 'QJA', age: 26 },
    { name: 'QAAA', age: 18 },
    { name: 'QBAA', age: 19 },
    { name: 'QCAA', age: 20 },
    { name: 'QDAA', age: 21 },
    { name: 'QEAA', age: 22 },
    { name: 'QFAA', age: 22 },
    { name: 'QGAA', age: 23 },
    { name: 'QHAA', age: 24 },
    { name: 'QIAA', age: 25 },
    { name: 'QJAA', age: 26 },
    { name: 'QAAAA', age: 18 },
    { name: 'QBAAA', age: 19 },
    { name: 'QCAAA', age: 20 },
    { name: 'QDAAA', age: 21 },
    { name: 'QEAAA', age: 22 },
    { name: 'QFAAA', age: 22 },
    { name: 'QGAAA', age: 23 },
    { name: 'QHAAA', age: 24 },
    { name: 'QIAAA', age: 25 },
    { name: 'QJAAA', age: 26 },
    { name: 'QAAAAA', age: 18 },
    { name: 'QBAAAA', age: 19 },
    { name: 'QCAAAA', age: 20 },
    { name: 'QDAAAA', age: 21 },
    { name: 'QEAAAA', age: 22 },
    { name: 'QFAAAA', age: 22 },
    { name: 'QGAAAA', age: 23 },
    { name: 'QHAAAA', age: 24 },
    { name: 'QIAAAA', age: 25 },
    { name: 'QJAAAA', age: 26 },
    { name: 'QQA', age: 18 },
    { name: 'QQB', age: 19 },
    { name: 'QQC', age: 20 },
    { name: 'QQD', age: 21 },
    { name: 'QQE', age: 22 },
    { name: 'QQF', age: 22 },
    { name: 'QQG', age: 23 },
    { name: 'QQH', age: 24 },
    { name: 'QQI', age: 25 },
    { name: 'QQJ', age: 26 },
    { name: 'QQAA', age: 18 },
    { name: 'QQBA', age: 19 },
    { name: 'QQCA', age: 20 },
    { name: 'QQDA', age: 21 },
    { name: 'QQEA', age: 22 },
    { name: 'QQFA', age: 22 },
    { name: 'QQGA', age: 23 },
    { name: 'QQHA', age: 24 },
    { name: 'QQIA', age: 25 },
    { name: 'QQJA', age: 26 },
    { name: 'QQAAA', age: 18 },
    { name: 'QQBAA', age: 19 },
    { name: 'QQCAA', age: 20 },
    { name: 'QQDAA', age: 21 },
    { name: 'QQEAA', age: 22 },
    { name: 'QQFAA', age: 22 },
    { name: 'QQGAA', age: 23 },
    { name: 'QQHAA', age: 24 },
    { name: 'QQIAA', age: 25 },
    { name: 'QQJAA', age: 26 },
    { name: 'QQAAAA', age: 18 },
    { name: 'QQBAAA', age: 19 },
    { name: 'QQCAAA', age: 20 },
    { name: 'QQDAAA', age: 21 },
    { name: 'QQEAAA', age: 22 },
    { name: 'QQFAAA', age: 22 },
    { name: 'QQGAAA', age: 23 },
    { name: 'QQHAAA', age: 24 },
    { name: 'QQIAAA', age: 25 },
    { name: 'QQJAAA', age: 26 },
    { name: 'QQAAAAA', age: 18 },
    { name: 'QQBAAAA', age: 19 },
    { name: 'QQCAAAA', age: 20 },
    { name: 'QQDAAAA', age: 21 },
    { name: 'QQEAAAA', age: 22 },
    { name: 'QQFAAAA', age: 22 },
    { name: 'QQGAAAA', age: 23 },
    { name: 'QQHAAAA', age: 24 },
    { name: 'QQIAAAA', age: 25 },
    { name: 'QQJAAAA', age: 26 },
    { name: 'QwA', age: 18 },
    { name: 'QwB', age: 19 },
    { name: 'QwC', age: 20 },
    { name: 'QwD', age: 21 },
    { name: 'QwE', age: 22 },
    { name: 'QwF', age: 22 },
    { name: 'QwG', age: 23 },
    { name: 'QwH', age: 24 },
    { name: 'QwI', age: 25 },
    { name: 'QwJ', age: 26 },
    { name: 'QwAA', age: 18 },
    { name: 'QwBA', age: 19 },
    { name: 'QwCA', age: 20 },
    { name: 'QwDA', age: 21 },
    { name: 'QwEA', age: 22 },
    { name: 'QwFA', age: 22 },
    { name: 'QwGA', age: 23 },
    { name: 'QwHA', age: 24 },
    { name: 'QwIA', age: 25 },
    { name: 'QwJA', age: 26 },
    { name: 'QwAAA', age: 18 },
    { name: 'QwBAA', age: 19 },
    { name: 'QwCAA', age: 20 },
    { name: 'QwDAA', age: 21 },
    { name: 'QwEAA', age: 22 },
    { name: 'QwFAA', age: 22 },
    { name: 'QwGAA', age: 23 },
    { name: 'QwHAA', age: 24 },
    { name: 'QwIAA', age: 25 },
    { name: 'QwJAA', age: 26 },
    { name: 'QwAAAA', age: 18 },
    { name: 'QwBAAA', age: 19 },
    { name: 'QwCAAA', age: 20 },
    { name: 'QwDAAA', age: 21 },
    { name: 'QwEAAA', age: 22 },
    { name: 'QwFAAA', age: 22 },
    { name: 'QwGAAA', age: 23 },
    { name: 'QwHAAA', age: 24 },
    { name: 'QwIAAA', age: 25 },
    { name: 'QwJAAA', age: 26 },
    { name: 'QwAAAAA', age: 18 },
    { name: 'QwBAAAA', age: 19 },
    { name: 'QwCAAAA', age: 20 },
    { name: 'QwDAAAA', age: 21 },
    { name: 'QwEAAAA', age: 22 },
    { name: 'QwFAAAA', age: 22 },
    { name: 'QwGAAAA', age: 23 },
    { name: 'QwHAAAA', age: 24 },
    { name: 'QwIAAAA', age: 25 },
    { name: 'QwJAAAA', age: 26 },
]

console.time(1)
obj1.forEach(ele => {
    let newEle = obj2.find(ele2 => ele2.name === ele.name)
    if (!newEle) {
        // console.log(`${ele.name} lost`);  riskPoint.push({type: 1, name: ele.name})
    } else {
        if (ele.age !== newEle.age) {
            // console.log(`${ele.name} age changed`); riskPoint.push({type: 2, name: ele.name})
        }
    }
})
console.timeEnd(1)

console.time(2)
let map1 = obj2.reduce((acc, curr) => {
    acc[curr.name] = curr
    return acc
}, {})

obj1.forEach(ele => {
    if (!map1[ele.name]) {
        // console.log(`${ele.name} lost`); riskPoint.push({type: 1, name: ele.name})
    } else {
        if (ele.age !== map1[ele.name].age) {
            // console.log(`${ele.name} age changed`); riskPoint.push({type: 2, name: ele.name})
        }
    }
})
console.timeEnd(2)